# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 450)
        Dialog.setMinimumSize(QtCore.QSize(700, 450))
        Dialog.setMaximumSize(QtCore.QSize(700, 450))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_header = QtWidgets.QFrame(Dialog)
        self.frame_header.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_header.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_header.setStyleSheet("background-image: url(:/header/Images/top_bar2.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.frame_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_header.setObjectName("frame_header")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_header)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_header)
        self.frame_body = QtWidgets.QFrame(Dialog)
        self.frame_body.setMinimumSize(QtCore.QSize(0, 290))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        self.frame_body.setFont(font)
        self.frame_body.setStyleSheet("background-color: rgb(65, 65, 65);\n"
"color: rgb(240, 255, 255);")
        self.frame_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_body.setObjectName("frame_body")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_body)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(25, -1, -1, -1)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.lineEdit_platform = QtWidgets.QLineEdit(self.frame_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_platform.sizePolicy().hasHeightForWidth())
        self.lineEdit_platform.setSizePolicy(sizePolicy)
        self.lineEdit_platform.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_platform.setMaximumSize(QtCore.QSize(650, 16777215))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        self.lineEdit_platform.setFont(font)
        self.lineEdit_platform.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_platform.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(42, 42, 59);\n"
"    border-left: 3px solid rgb(60, 60, 60);\n"
"    border-top: 3px solid rgb(60, 60, 60);\n"
"    background-color: rgb(40, 40, 40);\n"
"    height: 35px;\n"
"}\n"
"QLineEdit:hover {\n"
"        background-color: rgb(41, 41, 55);\n"
"\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(42, 42, 65);\n"
"    border-left: 3px solid rgb(60, 60, 60);\n"
"    border-top: 3px solid rgb(60, 60, 60);\n"
"    background-color: rgb(41, 41, 59);\n"
"\n"
"}")
        self.lineEdit_platform.setInputMask("")
        self.lineEdit_platform.setText("")
        self.lineEdit_platform.setMaxLength(32)
        self.lineEdit_platform.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_platform.setObjectName("lineEdit_platform")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_platform)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame_body)
        self.lineEdit_username.setMaximumSize(QtCore.QSize(650, 16777215))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(42, 42, 59);\n"
"    border-left: 3px solid rgb(60, 60, 60);\n"
"    border-top: 3px solid rgb(60, 60, 60);\n"
"    background-color: rgb(40, 40, 40);\n"
"    height: 35px;\n"
"}\n"
"QLineEdit:hover {\n"
"        background-color: rgb(41, 41, 55);\n"
"\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(42, 42, 65);\n"
"    border-left: 3px solid rgb(60, 60, 60);\n"
"    border-top: 3px solid rgb(60, 60, 60);\n"
"    background-color: rgb(41, 41, 59);\n"
"\n"
"}")
        self.lineEdit_username.setInputMask("")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setMaxLength(32)
        self.lineEdit_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_username)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_body)
        self.lineEdit_password.setMaximumSize(QtCore.QSize(650, 16777215))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(42, 42, 59);\n"
"    border-left: 3px solid rgb(60, 60, 60);\n"
"    border-top: 3px solid rgb(60, 60, 60);\n"
"    background-color: rgb(40, 40, 40);\n"
"    height: 35px;\n"
"}\n"
"QLineEdit:hover {\n"
"        background-color: rgb(41, 41, 55);\n"
"\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 3px solid rgb(42, 42, 65);\n"
"    border-left: 3px solid rgb(60, 60, 60);\n"
"    border-top: 3px solid rgb(60, 60, 60);\n"
"    background-color: rgb(41, 41, 59);\n"
"\n"
"}")
        self.lineEdit_password.setMaxLength(32)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_password)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMinimumSize(QtCore.QSize(220, 50))
        self.buttonBox.setMaximumSize(QtCore.QSize(220, 100))
        self.buttonBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setStyleSheet("background-color: rgb(100, 100, 100);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.frame_body)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_platform.setPlaceholderText(_translate("Dialog", "Platform"))
        self.lineEdit_username.setPlaceholderText(_translate("Dialog", "Username"))
        self.lineEdit_password.setPlaceholderText(_translate("Dialog", "Password"))
import resources_dialog_box
