# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(820, 848)
        login.setMinimumSize(QtCore.QSize(620, 700))
        login.setMaximumSize(QtCore.QSize(820, 1400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window_icon/C:/Users/Miguel/Desktop/Images/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        login.setWindowIcon(icon)
        login.setStyleSheet("color:rgb(240, 248, 255);\n"
"background-color: rgb(0, 0, 0);")
        login.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 35))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 45))
        self.top_bar.setStyleSheet("background-image: url(:/top_bar/top_bar2.png);\n"
"background-position:center")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.center = QtWidgets.QFrame(self.content)
        self.center.setMinimumSize(QtCore.QSize(0, 700))
        self.center.setMaximumSize(QtCore.QSize(600, 700))
        self.center.setStyleSheet("background-color: rgb(41, 41, 53);")
        self.center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center.setObjectName("center")
        self.frame_logo = QtWidgets.QFrame(self.center)
        self.frame_logo.setGeometry(QtCore.QRect(120, 90, 360, 90))
        self.frame_logo.setStyleSheet("background-image: url(:/logo/logo_360x90.png);\n"
"background-repeat:no-repeat;\n"
"background-position:center")
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.frame_pfp = QtWidgets.QFrame(self.center)
        self.frame_pfp.setGeometry(QtCore.QRect(240, 185, 120, 120))
        self.frame_pfp.setStyleSheet("QFrame {    \n"
"    background-image: url(:/profile-pic/avatar.png);\n"
"    border-radius:60px;\n"
"    border:3px solid rgb(255,207,0);\n"
"    background-position:center\n"
"}\n"
"}")
        self.frame_pfp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pfp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pfp.setObjectName("frame_pfp")
        self.lineEdit_login = QtWidgets.QLineEdit(self.center)
        self.lineEdit_login.setGeometry(QtCore.QRect(175, 320, 250, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        self.lineEdit_login.setFont(font)
        self.lineEdit_login.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(45, 45, 45);\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    border:2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(65, 65, 65);\n"
"}\n"
"QLineEdit:focus {\n"
"    color: rgb(200,200,200);\n"
"    padding:5px;\n"
"    background-color: rgb(65, 65, 65);\n"
"    border:2px solid rgb(255,207,0);\n"
"    \n"
"}")
        self.lineEdit_login.setMaxLength(32)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.lineEdit_pwd = QtWidgets.QLineEdit(self.center)
        self.lineEdit_pwd.setGeometry(QtCore.QRect(175, 375, 250, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        self.lineEdit_pwd.setFont(font)
        self.lineEdit_pwd.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(45, 45, 45);\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    border:2px solid rgb(55,55,55);\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: rgb(65, 65, 65);\n"
"\n"
"}\n"
"QLineEdit:focus {\n"
"    color: rgb(200,200,200);\n"
"    padding:5px;\n"
"    background-color: rgb(65, 65, 65);\n"
"    border:2px solid rgb(255,207,0);\n"
"    \n"
"}")
        self.lineEdit_pwd.setMaxLength(32)
        self.lineEdit_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pwd.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_pwd.setObjectName("lineEdit_pwd")
        self.checkBox_remember = QtWidgets.QCheckBox(self.center)
        self.checkBox_remember.setGeometry(QtCore.QRect(175, 430, 120, 25))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(10)
        self.checkBox_remember.setFont(font)
        self.checkBox_remember.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_remember.setStyleSheet("QCheckBox::indicator {\n"
"    border: 1px solid rgb(255, 207, 0);\n"
"    width:15px;\n"
"    height: 15px;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(65, 65, 65);\n"
"}\n"
"QCheckBox::indicator::checked {\n"
"    border: 1px solid rgb(255, 207, 0);\n"
"    background-color: rgb(209, 164, 1);\n"
"}")
        self.checkBox_remember.setObjectName("checkBox_remember")
        self.pushButton_enter = QtWidgets.QPushButton(self.center)
        self.pushButton_enter.setGeometry(QtCore.QRect(175, 500, 250, 50))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(11)
        self.pushButton_enter.setFont(font)
        self.pushButton_enter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_enter.setStyleSheet("QPushButton {\n"
"    background-color: rgb(45, 45, 45);\n"
"    border:2px solid rgb(55,55,55);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(65, 65, 65);\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(45, 45, 45);\n"
"    background-color: rgb(255, 207, 0);\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"}")
        self.pushButton_enter.setObjectName("pushButton_enter")
        self.frame_error = QtWidgets.QFrame(self.center)
        self.frame_error.setGeometry(QtCore.QRect(0, 0, 600, 30))
        self.frame_error.setMinimumSize(QtCore.QSize(600, 0))
        self.frame_error.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_error.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"border-radius: 5px;")
        self.frame_error.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setMidLineWidth(0)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_3.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_3.addWidget(self.label_error)
        self.pushButton_close_error = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_close_error.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_close_error.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_close_error.setStyleSheet("QPushButton {\n"
"    border-radius:5px;\n"
"    background-position:center;\n"
"    background-image: url(:/error-icon/cil-x.png);\n"
"    background-color: rgb(55, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color:rgb(200,200,200)\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);\n"
"    color:rgb(200,200,200)\n"
"}")
        self.pushButton_close_error.setText("")
        self.pushButton_close_error.setObjectName("pushButton_close_error")
        self.horizontalLayout_3.addWidget(self.pushButton_close_error)
        self.frame_error.raise_()
        self.frame_logo.raise_()
        self.frame_pfp.raise_()
        self.lineEdit_login.raise_()
        self.lineEdit_pwd.raise_()
        self.checkBox_remember.raise_()
        self.pushButton_enter.raise_()
        self.horizontalLayout.addWidget(self.center)
        self.verticalLayout.addWidget(self.content)
        self.bottom_bar = QtWidgets.QFrame(self.centralwidget)
        self.bottom_bar.setMaximumSize(QtCore.QSize(16777215, 45))
        self.bottom_bar.setStyleSheet("background-image: url(:/bottom_bar/background_bottom.png);\n"
"")
        self.bottom_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_bar.setObjectName("bottom_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom_bar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_credits = QtWidgets.QLabel(self.bottom_bar)
        self.label_credits.setStyleSheet("color: rgb(255, 207, 0);")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_2.addWidget(self.label_credits)
        self.verticalLayout.addWidget(self.bottom_bar)
        login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 21))
        self.menubar.setObjectName("menubar")
        login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login)
        self.statusbar.setObjectName("statusbar")
        login.setStatusBar(self.statusbar)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "login"))
        self.lineEdit_login.setPlaceholderText(_translate("login", "Username"))
        self.lineEdit_pwd.setPlaceholderText(_translate("login", "Password"))
        self.checkBox_remember.setText(_translate("login", "Remember me"))
        self.pushButton_enter.setText(_translate("login", "Enter"))
        self.label_error.setText(_translate("login", "Error"))
        self.label_credits.setText(_translate("login", "Created by Miguel Victor"))
import resources_login

